### ISSUE TITLE
.so CUDA version and tf.qr issue

### ISSUE THREAD

**Issue by qinenergy** [musikisomorphie/swd#1]
1. Seems that the binary files are built using CUDA 8.0 instead of 9.0.
```bash
Traceback (most recent call last):
  File "swgan_64x64.py", line 17, in <module>
    import tflib.ops.layers6
  File "/local/home/qwang/repos/swd/tflib/ops/layers6.py", line 6, in <module>
    my_ind = tf.load_op_library('cuda/indices_op.so')
  File "/local/home/qwang/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/local/home/qwang/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.8.0: cannot open shared object file: No such file or directory
```

Installing CUDA8 or building from source solves the problem.

2. tf.qr issue
cuSolver crashes when running into tf.qr, which is heavily used. Seems an upstream problem. tensorflow/tensorflow#20099

My workaround is to wrap all tf.qr with cpu allocation.
```python
with tf.device('/cpu:0'):
     tf.qr(...)
```

```bash
2019-04-16 20:57:49.124483: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x2b279740
2019-04-16 20:57:49.617085: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at qr_op_impl.h:211 : Internal: tensorflow/core/kernels/cuda_solvers.cc:468: cuSolverDN call failed with status =7
Traceback (most recent call last):
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: tensorflow/core/kernels/cuda_solvers.cc:468: cuSolverDN call failed with status =7
         [[Node: Encoder.swd2/Qr = Qr[T=DT_FLOAT, full_matrices=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Encoder.swd2/random_normal/mul)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "swae_64x64.py", line 434, in <module>
    train_model()
  File "swae_64x64.py", line 392, in train_model
    session.run(tf.global_variables_initializer())
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: tensorflow/core/kernels/cuda_solvers.cc:468: cuSolverDN call failed with status =7
         [[Node: Encoder.swd2/Qr = Qr[T=DT_FLOAT, full_matrices=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Encoder.swd2/random_normal/mul)]]

Caused by op 'Encoder.swd2/Qr', defined at:
  File "swae_64x64.py", line 434, in <module>
    train_model()
  File "swae_64x64.py", line 318, in train_model
    fake_z = BEGANEncoder(real_data)
  File "swae_64x64.py", line 299, in BEGANEncoder
    output = tflib.ops.layers6.SWDBlock('Encoder.swd2', output, noise, nbins=BIN)
  File "/local/home/qwang/repos/swd/tflib/ops/layers6.py", line 216, in SWDBlock
    weight_value, _ = tf.qr(tf.random_normal([ndepth, ndepth]))
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 1494, in qr
    "Qr", input=input, full_matrices=full_matrices, name=name)
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/local/home/qwang/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): tensorflow/core/kernels/cuda_solvers.cc:468: cuSolverDN call failed with status =7
         [[Node: Encoder.swd2/Qr = Qr[T=DT_FLOAT, full_matrices=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Encoder.swd2/random_normal/mul)]]
```

Testing environment:
gcc/++ 4.8
Tensorflow 1.10
CUDA 9.0
RTX 2080TI

**Comment by musikisomorphie** [comment]
@qinenergy, thank you for your feedback. I really appreciate it. Though I double checked my local cuda as well as our cluster cuda version, which are all cuda9.0. If my compiled .so files support cuda8.0, it supposes to report an error when I run it on our cluster.

Besides, we normally use Titan Xp or Titan X to train our model, this may cause difference as you mentioned that your environment is RTX 2080TI.

Anyway, I am glad you solve the problem and provide useful information which can potentially help other users. Thank you very much.

**Comment by qinenergy** [comment]
@musikisomorphie Thanks for the quick response >< I really like the code.


p.s. (not important tho)
Regarding the CUDA dependency, I still think it was built on cuda 8.0 :joy:
```bash
qwang@localgpu:~/repos/swd/cuda$ readelf -d gat1_op.so

Dynamic section at offset 0xdd90 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libcudart.so.8.0]
 0x0000000000000001 (NEEDED)             Shared library: [libtensorflow_framework.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x6c10
 0x000000000000000d (FINI)               0x9fec
 0x0000000000000019 (INIT_ARRAY)         0x20dce0
 0x000000000000001b (INIT_ARRAYSZ)       32 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x20dd00
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1f0
 0x0000000000000005 (STRTAB)             0x1f90
 0x0000000000000006 (SYMTAB)             0x778
 0x000000000000000a (STRSZ)              13688 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x20e000
 0x0000000000000002 (PLTRELSZ)           4416 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x5ad0
 0x0000000000000007 (RELA)               0x57a0
 0x0000000000000008 (RELASZ)             816 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x5710
 0x000000006fffffff (VERNEEDNUM)         3
 0x000000006ffffff0 (VERSYM)             0x5508
 0x000000006ffffff9 (RELACOUNT)          7
 0x0000000000000000 (NULL)               0x0
```

**Comment by musikisomorphie** [comment]
@qinenergy, you are correct. I will change the readme accordingly.

**Comment by qinenergy** [comment]
Thank you for sharing >w< LGTM !
